/*
 * WeatherAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using WeatherAPI.Standard;
using WeatherAPI.Standard.Utilities;


namespace WeatherAPI.Standard.Models
{
    public class Rain : BaseModel 
    {
        // These fields hold the values for the public properties.
        private double? m1h;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("1h")]
        public double? M1h 
        { 
            get 
            {
                return this.m1h; 
            } 
            set 
            {
                this.m1h = value;
                onPropertyChanged("M1h");
            }
        }
    }
} 